export const stories = [
  {
    id: 1,
    title: "The Red Cat",
    level: 1,
    difficulty: "easy",
    wordCount: 50,
    estimatedTime: "5 mins",
    thumbnail: "/cute-red-cat-illustration-for-children.jpg",
    content: [
      "The cat is red.",
      "The red cat sat.",
      "The cat sat on a mat.",
      "The red cat is big.",
      "The big red cat ran.",
      "The cat ran to Tom.",
      "Tom pet the red cat.",
      "The cat and Tom nap.",
    ],
  },
  {
    id: 2,
    title: "Sam's Big Day",
    level: 2,
    difficulty: "just-right",
    wordCount: 100,
    estimatedTime: "7 mins",
    thumbnail: "/happy-child-named-sam-having-fun.jpg",
    content: [
      "Sam woke up with a big smile.",
      "Today was going to be special.",
      "He jumped out of bed fast.",
      "Sam brushed his teeth and got dressed.",
      "Mom made pancakes for breakfast.",
      "They were his favorite kind.",
      "After eating, Sam went outside.",
      "His best friend was waiting there.",
      "They played games all morning long.",
      "It was the best day ever!",
    ],
  },
  {
    id: 3,
    title: "The Magic Garden",
    level: 3,
    difficulty: "challenge",
    wordCount: 150,
    estimatedTime: "10 mins",
    thumbnail: "/magical-garden-with-flowers-and-butterflies.jpg",
    content: [
      "Emma found a secret door in her backyard.",
      "She pushed it open and stepped through.",
      "Inside was the most beautiful garden she had ever seen.",
      "Flowers of every color bloomed everywhere.",
      "Butterflies danced in the warm sunshine.",
      "A small path led deeper into the garden.",
      "Emma followed it with wonder in her eyes.",
      "At the end stood a magnificent tree.",
      "Its leaves sparkled like tiny stars.",
      "Emma knew this place was truly magical.",
    ],
  },
]

export const mockEyeTrackingData = {
  gazeX: 0.5,
  gazeY: 0.5,
  isTracking: true,
  confidence: 0.95,
}

export const mockSessionData = {
  wordsRead: 127,
  newWordsLearned: 8,
  readingTime: "12 mins",
  accuracy: 94,
  struggledWords: ["together", "through", "beautiful", "magnificent"],
  confidenceScore: 87,
}
