export const stories = [
  {
    id: 1,
    title: "The Red Cat",
    level: 1,
    difficulty: "easy",
    wordCount: 50,
    estimatedTime: "5 mins",
    thumbnail: "/cute-red-cat-illustration-for-children.jpg",
    content: [
      "The cat is red.",
      "The red cat sat.",
      "The cat sat on a mat.",
      "The red cat is big.",
      "The big red cat ran.",
      "The cat ran to Tom.",
      "Tom pet the red cat.",
      "The cat and Tom nap.",
    ],
  },
  {
    id: 2,
    title: "Sam's Big Day",
    level: 2,
    difficulty: "just-right",
    wordCount: 100,
    estimatedTime: "7 mins",
    thumbnail: "/happy-child-named-sam-having-fun.jpg",
    content: [
      "Sam woke up with a big smile.",
      "Today was going to be special.",
      "He jumped out of bed fast.",
      "Sam brushed his teeth and got dressed.",
      "Mom made pancakes for breakfast.",
      "They were his favorite kind.",
      "After eating, Sam went outside.",
      "His best friend was waiting there.",
      "They played games all morning long.",
      "It was the best day ever!",
    ],
  },
  {
    id: 3,
    title: "The Magic Garden",
    level: 3,
    difficulty: "challenge",
    wordCount: 150,
    estimatedTime: "10 mins",
    thumbnail: "/magical-garden-with-flowers-and-butterflies.jpg",
    content: [
      "Emma found a secret door in her backyard.",
      "She pushed it open and stepped through.",
      "Inside was the most beautiful garden she had ever seen.",
      "Flowers of every color bloomed everywhere.",
      "Butterflies danced in the warm sunshine.",
      "A small path led deeper into the garden.",
      "Emma followed it with wonder in her eyes.",
      "At the end stood a magnificent tree.",
      "Its leaves sparkled like tiny stars.",
      "Emma knew this place was truly magical.",
    ],
  },
  {
    id: 4,
    title: "The Brave Little Explorer",
    level: 4,
    difficulty: "challenge",
    wordCount: 250,
    estimatedTime: "15 mins",
    thumbnail: "/girl-explorer-in-wilderness.jpg",
    content: [
      "Maya had always dreamed of becoming an explorer who would discover amazing places that nobody had ever seen before.",
      "One sunny morning, she packed her backpack with a compass, a notebook, some snacks, and a bottle of water for her adventure.",
      "She walked through the forest behind her house, carefully observing the tall trees, colorful birds, and interesting insects along the way.",
      "After walking for what felt like hours, Maya discovered a sparkling stream that wound its way through the mossy rocks and ferns.",
      "She followed the stream upstream, wondering where it came from and what secrets it might reveal to her.",
      "Suddenly, Maya heard a strange sound coming from behind a large boulder covered in soft green moss.",
      "She carefully climbed over the rocks and found a small cave entrance that seemed to glow with a mysterious golden light.",
      "Taking a deep breath to calm her nerves, Maya stepped inside the cave and gasped at what she saw.",
      "The walls were covered with beautiful crystals that sparkled like diamonds in the sunlight streaming through cracks in the ceiling.",
      "Maya wrote everything down in her notebook, knowing that she had made an incredible discovery that she would remember forever.",
    ],
  },
  {
    id: 5,
    title: "The Friendship Festival",
    level: 4,
    difficulty: "challenge",
    wordCount: 280,
    estimatedTime: "16 mins",
    thumbnail: "/friends-at-festival.jpg",
    content: [
      "Every year in the small town of Willowbrook, the community gathered together to celebrate the Friendship Festival, a special event that brought everyone closer.",
      "This year, twins Alex and Jordan were chosen to help organize the festival, which meant they had many important responsibilities to handle.",
      "They started by creating colorful posters and hanging them all around town so that everyone would know when and where the festival would take place.",
      "Alex suggested they should have different activity stations including face painting, balloon animals, a baking contest, and musical performances throughout the day.",
      "Jordan thought it would be wonderful to invite people to share stories about their best friends and what friendship meant to them personally.",
      "On the morning of the festival, the town square was transformed into a magical wonderland with decorations, food stands, and game booths everywhere you looked.",
      "Children ran excitedly from one activity to another, their laughter filling the air and creating an atmosphere of pure joy and happiness.",
      "The mayor gave a heartwarming speech about how friendship makes communities stronger and helps people support each other during difficult times.",
      "As the sun began to set, everyone gathered in a big circle, held hands, and sang songs together under the twinkling stars.",
      "Alex and Jordan looked at each other and smiled, knowing that they had helped create memories that would last a lifetime for everyone in Willowbrook.",
    ],
  },
  {
    id: 6,
    title: "The Mystery of the Missing Telescope",
    level: 5,
    difficulty: "challenge",
    wordCount: 320,
    estimatedTime: "18 mins",
    thumbnail: "/telescope-astronomy.jpg",
    content: [
      "Professor Chen was a brilliant astronomer who spent every clear night studying the stars, planets, and galaxies through her powerful telescope at the university observatory.",
      "One Tuesday morning, when she arrived at the observatory to prepare for that evening's observations, she discovered that her precious telescope had mysteriously disappeared without a trace.",
      "She immediately called her assistant, Marcus, who rushed over to help investigate the strange disappearance and figure out what could have possibly happened.",
      "Together, they carefully examined the observatory for clues, looking for anything unusual like footprints, fingerprints, or signs that someone had broken in during the night.",
      "Marcus noticed that the security camera had been turned off at exactly midnight, which seemed very suspicious and suggested that someone had planned this carefully.",
      "Professor Chen remembered that she had been working on an important discovery about a new comet, and she wondered if someone wanted to steal her research along with the telescope.",
      "They decided to interview everyone who had access to the observatory, including other professors, graduate students, and the night security guard who patrolled the building.",
      "During the interviews, they learned that a visiting scientist from another university had been asking many questions about Professor Chen's telescope and research just days before.",
      "Marcus and Professor Chen tracked down the visiting scientist and found him at a hotel, where he nervously admitted that he had borrowed the telescope without permission because his own had broken.",
      "The scientist apologized sincerely and explained that he had planned to return it before anyone noticed, but he realized now that what he did was wrong and he should have simply asked for help instead.",
      "Professor Chen forgave him but explained the importance of honesty and communication in the scientific community, and together they all worked to ensure nothing like this would ever happen again.",
    ],
  },
]

export const mockEyeTrackingData = {
  gazeX: 0.5,
  gazeY: 0.5,
  isTracking: true,
  confidence: 0.95,
}

export const mockSessionData = {
  wordsRead: 127,
  newWordsLearned: 8,
  readingTime: "12 mins",
  accuracy: 94,
  struggledWords: ["together", "through", "beautiful", "magnificent"],
  confidenceScore: 87,
}
